export const getAllEnzymes = (() =>{
const enzymes =  [{ name: 'BseX3I', reg: 'cggccg', len: 6 },
  { name: 'AseII', reg: 'cc[cg]gg', len: 5 },
  { name: 'MspR9I', reg: 'cc[actg]gg', len: 5 },
  { name: 'SacI', reg: 'gagctc', len: 6 },
  { name: 'Tth111I', reg: 'gac[actg][actg][actg]gtc', len: 9 },
  { name: 'Alw44I', reg: 'gtgcac', len: 6 },
  { name: 'EcoO109I', reg: '[ag]gg[actg]cc[ct]', len: 7 },
  { name: 'MboI', reg: 'gatc', len: 4 },
  { name: 'Vha464I', reg: 'cttaag', len: 6 },
  { name: 'NlaIII', reg: 'catg', len: 4 },
  { name: 'CspAI', reg: 'accggt', len: 6 },
  { name: 'FunII', reg: 'gaattc', len: 6 },
  { name: 'MamI', reg: 'gat[actg][actg][actg][actg]atc', len: 10 },
  { name: 'SspBI', reg: 'tgtaca', len: 6 },
  { name: 'BsiHKAI', reg: 'g[at]gc[at]c', len: 6 },
  { name: 'Bme1580I', reg: 'g[gt]gc[ac]c', len: 6 },
  { name: 'BseBI', reg: 'cc[at]gg', len: 5 },
  { name: 'SalI', reg: 'gtcgac', len: 6 },
  { name: 'Van91I',
    reg: 'cca[actg][actg][actg][actg][actg]tgg',
    len: 11 },
  { name: 'ApeKI', reg: 'gc[at]gc', len: 5 },
  { name: 'MspA1I', reg: 'c[ac]gc[gt]g', len: 6 },
  { name: 'MwoI',
    reg: 'gc[actg][actg][actg][actg][actg][actg][actg]gc',
    len: 11 },
  { name: 'SphI', reg: 'gcatgc', len: 6 },
  { name: 'BseSI', reg: 'g[gt]gc[ac]c', len: 6 },
  { name: 'NlaIV', reg: 'gg[actg][actg]cc', len: 6 },
  { name: 'Bsp143I', reg: 'gatc', len: 4 },
  { name: 'AccB1I', reg: 'gg[ct][ag]cc', len: 6 },
  { name: 'Kpn2I', reg: 'tccgga', len: 6 },
  { name: 'Cfr9I', reg: 'cccggg', len: 6 },
  { name: 'BssT1I', reg: 'cc[at][at]gg', len: 6 },
  { name: 'PceI', reg: 'aggcct', len: 6 },
  { name: 'DseDI',
    reg: 'gac[actg][actg][actg][actg][actg][actg]gtc',
    len: 12 },
  { name: 'Bpu14I', reg: 'ttcgaa', len: 6 },
  { name: 'Bst4CI', reg: 'ac[actg]gt', len: 5 },
  { name: 'EagI', reg: 'cggccg', len: 6 },
  { name: 'ErhI', reg: 'cc[at][at]gg', len: 6 },
  { name: 'AleI', reg: 'cac[actg][actg][actg][actg]gtg', len: 10 },
  { name: 'Hin1I', reg: 'g[ag]cg[ct]c', len: 6 },
  { name: 'XmnI', reg: 'gaa[actg][actg][actg][actg]ttc', len: 10 },
  { name: 'BstMBI', reg: 'gatc', len: 4 },
  { name: 'TelI', reg: 'gac[actg][actg][actg]gtc', len: 9 },
  { name: 'BstYI', reg: '[ag]gatc[ct]', len: 6 },
  { name: 'MfeI', reg: 'caattg', len: 6 },
  { name: 'PmaCI', reg: 'cacgtg', len: 6 },
  { name: 'Alw21I', reg: 'g[at]gc[at]c', len: 6 },
  { name: 'Bse8I', reg: 'gat[actg][actg][actg][actg]atc', len: 10 },
  { name: 'NdeI', reg: 'catatg', len: 6 },
  { name: 'PdiI', reg: 'gccggc', len: 6 },
  { name: 'Bme1390I', reg: 'cc[actg]gg', len: 5 },
  { name: 'VpaK11BI', reg: 'gg[at]cc', len: 5 },
  { name: 'BstDSI', reg: 'cc[ag][ct]gg', len: 6 },
  { name: 'Bsp143II', reg: '[ag]gcgc[ct]', len: 6 },
  { name: 'DrdI',
    reg: 'gac[actg][actg][actg][actg][actg][actg]gtc',
    len: 12 },
  { name: 'Hpy188III', reg: 'tc[actg][actg]ga', len: 6 },
  { name: 'AvaI', reg: 'c[ct]cg[ag]g', len: 6 },
  { name: 'AatII', reg: 'gacgtc', len: 6 },
  { name: 'Bsp68I', reg: 'tcgcga', len: 6 },
  { name: 'BstEII', reg: 'ggt[actg]acc', len: 7 },
  { name: 'ApaI', reg: 'gggccc', len: 6 },
  { name: 'AasI',
    reg: 'gac[actg][actg][actg][actg][actg][actg]gtc',
    len: 12 },
  { name: 'AxyI', reg: 'cct[actg]agg', len: 7 },
  { name: 'TseI', reg: 'gc[at]gc', len: 5 },
  { name: 'CviAII', reg: 'catg', len: 4 },
  { name: 'BssAI', reg: '[ag]ccgg[ct]', len: 6 },
  { name: 'ApoI', reg: '[ag]aatt[ct]', len: 6 },
  { name: 'BcuI', reg: 'actagt', len: 6 },
  { name: 'Bse21I', reg: 'cct[actg]agg', len: 7 },
  { name: 'SexAI', reg: 'acc[at]ggt', len: 7 },
  { name: 'TauI', reg: 'gc[cg]gc', len: 5 },
  { name: 'BsaBI', reg: 'gat[actg][actg][actg][actg]atc', len: 10 },
  { name: 'NaeI', reg: 'gccggc', len: 6 },
  { name: 'AccB7I',
    reg: 'cca[actg][actg][actg][actg][actg]tgg',
    len: 11 },
  { name: 'Eco81I', reg: 'cct[actg]agg', len: 7 },
  { name: 'BsuTUI', reg: 'atcgat', len: 6 },
  { name: 'BssKI', reg: 'cc[actg]gg', len: 5 },
  { name: 'BtgI', reg: 'cc[ag][ct]gg', len: 6 },
  { name: 'BstDEI', reg: 'ct[actg]ag', len: 5 },
  { name: 'Hsp92II', reg: 'catg', len: 4 },
  { name: 'PaeR7I', reg: 'ctcgag', len: 6 },
  { name: 'MunI', reg: 'caattg', len: 6 },
  { name: 'BsiWI', reg: 'cgtacg', len: 6 },
  { name: 'BstUI', reg: 'cgcg', len: 4 },
  { name: 'Eco88I', reg: 'c[ct]cg[ag]g', len: 6 },
  { name: 'DpnII', reg: 'gatc', len: 4 },
  { name: 'MhlI', reg: 'g[agt]gc[act]c', len: 6 },
  { name: 'Bsh1285I', reg: 'cg[ag][ct]cg', len: 6 },
  { name: 'BalI', reg: 'tggcca', len: 6 },
  { name: 'NciI', reg: 'cc[cg]gg', len: 5 },
  { name: 'Bsp119I', reg: 'ttcgaa', len: 6 },
  { name: 'Fnu4HI', reg: 'gc[actg]gc', len: 5 },
  { name: 'BsrFI', reg: '[ag]ccgg[ct]', len: 6 },
  { name: 'EclXI', reg: 'cggccg', len: 6 },
  { name: 'StyD4I', reg: 'cc[actg]gg', len: 5 },
  { name: 'FunI', reg: 'agcgct', len: 6 },
  { name: 'BseCI', reg: 'atcgat', len: 6 },
  { name: 'Acc16I', reg: 'tgcgca', len: 6 },
  { name: 'AspLEI', reg: 'gcgc', len: 4 }, 
  { name: 'AsiSI', reg: 'gcgatcgc', len: 8 },
  { name: 'BspDI', reg: 'atcgat', len: 6 },
  { name: 'BstZI', reg: 'cggccg', len: 6 },
  { name: 'SacII', reg: 'ccgcgg', len: 6 },
  { name: 'CspI', reg: 'cgg[at]ccg', len: 7 },
  { name: 'Tsp45I', reg: 'gt[cg]ac', len: 5 },
  { name: 'Bsp107I', reg: 'ctgcag', len: 6 },
  { name: 'AcyI', reg: 'g[ag]cg[ct]c', len: 6 },
  { name: 'AhlI', reg: 'actagt', len: 6 },
  { name: 'Sau96I', reg: 'gg[actg]cc', len: 5 },
  { name: 'TaqI', reg: 'tcga', len: 4 },
  { name: 'SseBI', reg: 'aggcct', len: 6 },
  { name: 'EaeI', reg: '[ct]ggcc[ag]', len: 6 },
  { name: 'PspLI', reg: 'cgtacg', len: 6 },
  { name: 'Hpy99I', reg: 'cg[at]cg', len: 5 },
  { name: 'VneI', reg: 'gtgcac', len: 6 },
  { name: 'AspHI', reg: 'g[at]gc[at]c', len: 6 },
  { name: 'PspOMI', reg: 'gggccc', len: 6 },
  { name: 'HinfI', reg: 'ga[actg]tc', len: 5 },
  { name: 'AccII', reg: 'cgcg', len: 4 },
  { name: 'PmeI', reg: 'gtttaaac', len: 8 },
  { name: 'TasI', reg: 'aatt', len: 4 },
  { name: 'BstSCI', reg: 'cc[actg]gg', len: 5 },
  { name: 'BstACI', reg: 'g[ag]cg[ct]c', len: 6 },
  { name: 'EcoT22I', reg: 'atgcat', len: 6 },
  { name: 'PspCI', reg: 'cacgtg', len: 6 },
  { name: 'SpaHI', reg: 'gcatgc', len: 6 },
  { name: 'EcoRI', reg: 'gaattc', len: 6 },
  { name: 'FspI', reg: 'tgcgca', len: 6 },
  { name: 'HpyCH4III', reg: 'ac[actg]gt', len: 5 },
  { name: 'BstBAI', reg: '[ct]acgt[ag]', len: 6 },
  { name: 'Psp5II', reg: '[ag]gg[at]cc[ct]', len: 7 },
  { name: 'PspPPI', reg: '[ag]gg[at]cc[ct]', len: 7 },
  { name: 'PciI', reg: 'acatgt', len: 6 },
  { name: 'TliI', reg: 'ctcgag', len: 6 },
  { name: 'PflMI',
    reg: 'cca[actg][actg][actg][actg][actg]tgg',
    len: 11 },
  { name: 'HindII', reg: 'gt[ct][ag]ac', len: 6 },
  { name: 'BspLU11I', reg: 'acatgt', len: 6 },
  { name: 'ScrFI', reg: 'cc[actg]gg', len: 5 },
  { name: 'Eco47I', reg: 'gg[at]cc', len: 5 },
  { name: 'NcoI', reg: 'ccatgg', len: 6 },
  { name: 'Bsp1720I', reg: 'gct[actg]agc', len: 7 },
  { name: 'SwaI', reg: 'atttaaat', len: 8 },
  { name: 'BstKTI', reg: 'gatc', len: 4 },
  { name: 'NspV', reg: 'ttcgaa', len: 6 },
  { name: 'TscI', reg: 'acgt', len: 4 },
  { name: 'Bsp120I', reg: 'gggccc', len: 6 },
  { name: 'BsrGI', reg: 'tgtaca', len: 6 },
  { name: 'Eco52I', reg: 'cggccg', len: 6 },
  { name: 'MluNI', reg: 'tggcca', len: 6 },
  { name: 'AseI', reg: 'attaat', len: 6 },
  { name: 'AsuNHI', reg: 'gctagc', len: 6 },
  { name: 'Eco91I', reg: 'ggt[actg]acc', len: 7 },
  { name: 'EcoO65I', reg: 'ggt[actg]acc', len: 7 },
  { name: 'AvrII', reg: 'cctagg', len: 6 },
  { name: 'Sau3AI', reg: 'gatc', len: 4 },
  { name: 'ZraI', reg: 'gacgtc', len: 6 },
  { name: 'Tru1I', reg: 'ttaa', len: 4 },
  { name: 'CfoI', reg: 'gcgc', len: 4 },
  { name: 'Eam1105I',
    reg: 'gac[actg][actg][actg][actg][actg]gtc',
    len: 11 },
  { name: 'BspT107I', reg: 'gg[ct][ag]cc', len: 6 },
  { name: 'BanIII', reg: 'atcgat', len: 6 },
  { name: 'MaeII', reg: 'acgt', len: 4 },
  { name: 'AflII', reg: 'cttaag', len: 6 },
  { name: 'FspBI', reg: 'ctag', len: 4 },
  { name: 'HspAI', reg: 'gcgc', len: 4 },
  { name: 'PstI', reg: 'ctgcag', len: 6 },
  { name: 'SatI', reg: 'gc[actg]gc', len: 5 },
  { name: 'PpuMI', reg: '[ag]gg[at]cc[ct]', len: 7 },
  { name: 'KasI', reg: 'ggcgcc', len: 6 },
  { name: 'Bpu1102I', reg: 'gct[actg]agc', len: 7 },
  { name: 'Csp45I', reg: 'ttcgaa', len: 6 },
  { name: 'MspCI', reg: 'cttaag', len: 6 },
  { name: 'MvaI', reg: 'cc[at]gg', len: 5 },
  { name: 'HpaII', reg: 'ccgg', len: 4 },
  { name: 'BsoBI', reg: 'c[ct]cg[ag]g', len: 6 },
  { name: 'AccI', reg: 'gt[ac][gt]ac', len: 6 },
  { name: 'EcoRII', reg: 'cc[at]gg', len: 5 },
  { name: 'Sfr274I', reg: 'ctcgag', len: 6 },
  { name: 'PinAI', reg: 'accggt', len: 6 },
  { name: 'HpyF10VI',
    reg: 'gc[actg][actg][actg][actg][actg][actg][actg]gc',
    len: 11 },
  { name: 'BseDI', reg: 'cc[actg][actg]gg', len: 6 },
  { name: 'Mph1103I', reg: 'atgcat', len: 6 },
  { name: 'Asp718I', reg: 'ggtacc', len: 6 },
  { name: 'BsaJI', reg: 'cc[actg][actg]gg', len: 6 },
  { name: 'DraI', reg: 'tttaaa', len: 6 },
  { name: 'Eco24I', reg: 'g[ag]gc[ct]c', len: 6 },
  { name: 'NheI', reg: 'gctagc', len: 6 },
  { name: 'BstPAI',
    reg: 'gac[actg][actg][actg][actg]gtc',
    len: 10 },
  { name: 'NarI', reg: 'ggcgcc', len: 6 },
  { name: 'BsePI', reg: 'gcgcgc', len: 6 },
  { name: 'SfuI', reg: 'ttcgaa', len: 6 },
  { name: 'EcoT14I', reg: 'cc[at][at]gg', len: 6 },
  { name: 'PspPI', reg: 'gg[actg]cc', len: 5 },
  { name: 'SdaI', reg: 'cctgcagg', len: 8 },
  { name: 'XagI',
    reg: 'cct[actg][actg][actg][actg][actg]agg',
    len: 11 },
  { name: 'AatI', reg: 'aggcct', len: 6 },
  { name: 'Pfl23II', reg: 'cgtacg', len: 6 },
  { name: 'CaiI', reg: 'cag[actg][actg][actg]ctg', len: 9 },
  { name: 'Mly113I', reg: 'ggcgcc', len: 6 },
  { name: 'BspEI', reg: 'tccgga', len: 6 },
  { name: 'AspEI',
    reg: 'gac[actg][actg][actg][actg][actg]gtc',
    len: 11 },
  { name: 'MflI', reg: '[ag]gatc[ct]', len: 6 },
  { name: 'BstENI',
    reg: 'cct[actg][actg][actg][actg][actg]agg',
    len: 11 },
  { name: 'BstX2I', reg: '[ag]gatc[ct]', len: 6 },
  { name: 'BseLI',
    reg: 'cc[actg][actg][actg][actg][actg][actg][actg]gg',
    len: 11 },
  { name: 'Hpy8I', reg: 'gt[actg][actg]ac', len: 6 },
  { name: 'BspHI', reg: 'tcatga', len: 6 },
  { name: 'Aor51HI', reg: 'agcgct', len: 6 },
  { name: 'SstI', reg: 'gagctc', len: 6 },
  { name: 'BamHI', reg: 'ggatcc', len: 6 },
  { name: 'Cfr42I', reg: 'ccgcgg', len: 6 },
  { name: 'XbaI', reg: 'tctaga', len: 6 },
  { name: 'PshBI', reg: 'attaat', len: 6 },
  { name: 'AflIII', reg: 'ac[ag][ct]gt', len: 6 },
  { name: 'BfrBI', reg: 'atgcat', len: 6 },
  { name: 'SunI', reg: 'cgtacg', len: 6 },
  { name: 'ApaLI', reg: 'gtgcac', len: 6 },
  { name: 'HincII', reg: 'gt[ct][ag]ac', len: 6 },
  { name: 'BstC8I', reg: 'gc[actg][actg]gc', len: 6 },
  { name: 'BstOI', reg: 'cc[at]gg', len: 5 },
  { name: 'AsuC2I', reg: 'cc[cg]gg', len: 5 },
  { name: 'XmaI', reg: 'cccggg', len: 6 },
  { name: 'BshFI', reg: 'ggcc', len: 4 },
  { name: 'KpnI', reg: 'ggtacc', len: 6 },
  { name: 'PspAI', reg: 'cccggg', len: 6 },
  { name: 'MroI', reg: 'tccgga', len: 6 },
  { name: 'Eco147I', reg: 'aggcct', len: 6 },
  { name: 'Ple19I', reg: 'cgatcg', len: 6 },
  { name: 'BseJI', reg: 'gat[actg][actg][actg][actg]atc', len: 10 },
  { name: 'BcnI', reg: 'cc[cg]gg', len: 5 },
  { name: 'PsyI', reg: 'gac[actg][actg][actg]gtc', len: 9 },
  { name: 'AvaII', reg: 'gg[at]cc', len: 5 },
  { name: 'Eco130I', reg: 'cc[at][at]gg', len: 6 },
  { name: 'PspN4I', reg: 'gg[actg][actg]cc', len: 6 },
  { name: 'Ama87I', reg: 'c[ct]cg[ag]g', len: 6 },
  { name: 'XmaCI', reg: 'cccggg', len: 6 },
  { name: 'BlpI', reg: 'gct[actg]agc', len: 7 },
  { name: 'BoxI', reg: 'gac[actg][actg][actg][actg]gtc', len: 10 },
  { name: 'SgfI', reg: 'gcgatcgc', len: 8 },
  { name: 'AluI', reg: 'agct', len: 4 },
  { name: 'BfuCI', reg: 'gatc', len: 4 },
  { name: 'Bsa29I', reg: 'atcgat', len: 6 },
  { name: 'BssECI', reg: 'cc[actg][actg]gg', len: 6 },
  { name: 'CpoI', reg: 'cgg[at]ccg', len: 7 },
  { name: 'Psp1406I', reg: 'aacgtt', len: 6 },
  { name: 'BanI', reg: 'gg[ct][ag]cc', len: 6 },
  { name: 'HaeII', reg: '[ag]gcgc[ct]', len: 6 },
  { name: 'BstAUI', reg: 'tgtaca', len: 6 },
  { name: 'BshTI', reg: 'accggt', len: 6 },
  { name: 'EgeI', reg: 'ggcgcc', len: 6 },
  { name: 'NmuCI', reg: 'gt[cg]ac', len: 5 },
  { name: 'BstSFI', reg: 'ct[ag][ct]ag', len: 6 },
  { name: 'Bsp106I', reg: 'atcgat', len: 6 },
  { name: 'AlwI', reg: 'ggatc', len: 5 },
  { name: 'MaeI', reg: 'ctag', len: 4 },
  { name: 'CelII', reg: 'gct[actg]agc', len: 7 },
  { name: 'RcaI', reg: 'tcatga', len: 6 },
  { name: 'Bsp1407I', reg: 'tgtaca', len: 6 },
  { name: 'Hin6I', reg: 'gcgc', len: 4 },
  { name: 'MssI', reg: 'gtttaaac', len: 8 },
  { name: 'Bsu15I', reg: 'atcgat', len: 6 },
  { name: 'Bsc4I',
    reg: 'cc[actg][actg][actg][actg][actg][actg][actg]gg',
    len: 11 },
  { name: 'KspAI', reg: 'gttaac', len: 6 },
  { name: 'ItaI', reg: 'gc[actg]gc', len: 5 },
  { name: 'PflBI',
    reg: 'cca[actg][actg][actg][actg][actg]tgg',
    len: 11 },
  { name: 'HaeIII', reg: 'ggcc', len: 4 },
  { name: 'NdeII', reg: 'gatc', len: 4 },
  { name: 'NotI', reg: 'gcggccgc', len: 8 },
  { name: 'FriOI', reg: 'g[ag]gc[ct]c', len: 6 },
  { name: 'AhdI',
    reg: 'gac[actg][actg][actg][actg][actg]gtc',
    len: 11 },
  { name: 'BstMWI',
    reg: 'gc[actg][actg][actg][actg][actg][actg][actg]gc',
    len: 11 },
  { name: 'Kzo9I', reg: 'gatc', len: 4 },
  { name: 'BssNAI', reg: 'gtatac', len: 6 },
  { name: 'SinI', reg: 'gg[at]cc', len: 5 },
  { name: 'AjnI', reg: 'cc[at]gg', len: 5 },
  { name: 'MabI', reg: 'acc[at]ggt', len: 7 },
  { name: 'DdeI', reg: 'ct[actg]ag', len: 5 },
  { name: 'AspI', reg: 'gac[actg][actg][actg]gtc', len: 9 },
  { name: 'Bme18I', reg: 'gg[at]cc', len: 5 },
  { name: 'ScaI', reg: 'agtact', len: 6 },
  { name: 'Bsp1286I', reg: 'g[agt]gc[act]c', len: 6 },
  { name: 'TaiI', reg: 'acgt', len: 4 },
  { name: 'Bsp13I', reg: 'tccgga', len: 6 },
  { name: 'BclI', reg: 'tgatca', len: 6 },
  { name: 'TfiI', reg: 'ga[at]tc', len: 5 },
  { name: 'BstFNI', reg: 'cgcg', len: 4 },
  { name: 'OliI', reg: 'cac[actg][actg][actg][actg]gtg', len: 10 },
  { name: 'SmiI', reg: 'atttaaat', len: 8 },
  { name: 'SgrAI', reg: 'c[ag]ccgg[ct]g', len: 8 },
  { name: 'Psp124BI', reg: 'gagctc', len: 6 },
  { name: 'XceI', reg: '[ag]catg[ct]', len: 6 },
  { name: 'MvnI', reg: 'cgcg', len: 4 },
  { name: 'BsiSI', reg: 'ccgg', len: 4 },
  { name: 'Zsp2I', reg: 'atgcat', len: 6 },
  { name: 'AvrI', reg: 'c[ct]cg[ag]g', len: 6 },
  { name: 'BspT104I', reg: 'ttcgaa', len: 6 },
  { name: 'PagI', reg: 'tcatga', len: 6 },
  { name: 'BseAI', reg: 'tccgga', len: 6 },
  { name: 'RsrII', reg: 'cgg[at]ccg', len: 7 },
  { name: 'Ksp22I', reg: 'tgatca', len: 6 },
  { name: 'PdmI', reg: 'gaa[actg][actg][actg][actg]ttc', len: 10 },
  { name: 'FbaI', reg: 'tgatca', len: 6 },
  { name: 'StuI', reg: 'aggcct', len: 6 },
  { name: 'PfeI', reg: 'ga[at]tc', len: 5 },
  { name: 'ZhoI', reg: 'atcgat', len: 6 },
  { name: 'PmlI', reg: 'cacgtg', len: 6 },
  { name: 'BshNI', reg: 'gg[ct][ag]cc', len: 6 },
  { name: 'EclHKI',
    reg: 'gac[actg][actg][actg][actg][actg]gtc',
    len: 11 },
  { name: 'CciNI', reg: 'gcggccgc', len: 8 },
  { name: 'Psp6I', reg: 'cc[at]gg', len: 5 },
  { name: 'BbeI', reg: 'ggcgcc', len: 6 },
  { name: 'PspEI', reg: 'ggt[actg]acc', len: 7 },
  { name: 'AsiI', reg: 'ggatcc', len: 6 },
  { name: 'AlwNI', reg: 'cag[actg][actg][actg]ctg', len: 9 },
  { name: 'HapII', reg: 'ccgg', len: 4 },
  { name: 'XmiI', reg: 'gt[ac][gt]ac', len: 6 },
  { name: 'Bse118I', reg: '[ag]ccgg[ct]', len: 6 },
  { name: 'SmiMI',
    reg: 'ca[ct][actg][actg][actg][actg][ag]tg',
    len: 10 },
  { name: 'Bsu36I', reg: 'cct[actg]agg', len: 7 },
  { name: 'NruI', reg: 'tcgcga', len: 6 },
  { name: 'HpyCH4V', reg: 'tgca', len: 4 },
  { name: 'MroXI', reg: 'gaa[actg][actg][actg][actg]ttc', len: 10 },
  { name: 'AfeI', reg: 'agcgct', len: 6 },
  { name: 'HindIII', reg: 'aagctt', len: 6 },
  { name: 'PspGI', reg: 'cc[at]gg', len: 5 },
  { name: 'CviTI', reg: '[ag]gc[ct]', len: 4 },
  { name: 'BfmI', reg: 'ct[ag][ct]ag', len: 6 },
{ name: 'HpaI', reg: 'gttaac', len: 6 },
  { name: 'BmyI', reg: 'g[agt]gc[act]c', len: 6 },
  { name: 'SmaI', reg: 'cccggg', len: 6 },
  { name: 'AsiAI', reg: 'accggt', len: 6 },
  { name: 'BstAPI',
    reg: 'gca[actg][actg][actg][actg][actg]tgc',
    len: 11 },
  { name: 'Cfr13I', reg: 'gg[actg]cc', len: 5 },
  { name: 'CviJI', reg: '[ag]gc[ct]', len: 4 },
  { name: 'BstBI', reg: 'ttcgaa', len: 6 },
  { name: 'DpnI', reg: 'gatc', len: 4 },
  { name: 'BssHII', reg: 'gcgcgc', len: 6 },
  { name: 'ClaI', reg: 'atcgat', len: 6 },
  { name: 'Bst1107I', reg: 'gtatac', len: 6 },
  { name: 'BanII', reg: 'g[ag]gc[ct]c', len: 6 },
  { name: 'SfcI', reg: 'ct[ag][ct]ag', len: 6 },
  { name: 'PshAI', reg: 'gac[actg][actg][actg][actg]gtc', len: 10 },
  { name: 'PsuI', reg: '[ag]gatc[ct]', len: 6 },
  { name: 'Rsr2I', reg: 'cgg[at]ccg', len: 7 },
  { name: 'BstMCI', reg: 'cg[ag][ct]cg', len: 6 },
  { name: 'EcoT38I', reg: 'g[ag]gc[ct]c', len: 6 },
  { name: 'MslI',
    reg: 'ca[ct][actg][actg][actg][actg][ag]tg',
    len: 10 },
  { name: 'SgrBI', reg: 'ccgcgg', len: 6 },
  { name: 'BsiHKCI', reg: 'c[ct]cg[ag]g', len: 6 },
  { name: 'BstXI',
    reg: 'cca[actg][actg][actg][actg][actg][actg]tgg',
    len: 12 },
  { name: 'AdeI', reg: 'cac[actg][actg][actg]gtg', len: 9 },
  { name: 'BsiEI', reg: 'cg[ag][ct]cg', len: 6 },
  { name: 'XhoII', reg: '[ag]gatc[ct]', len: 6 },
  { name: 'AfaI', reg: 'gtac', len: 4 },
  { name: 'Msp20I', reg: 'tggcca', len: 6 },
  { name: 'NspI', reg: '[ag]catg[ct]', len: 6 },
  { name: 'PvuII', reg: 'cagctg', len: 6 },
  { name: 'BssHI', reg: 'ctcgag', len: 6 },
  { name: 'AclI', reg: 'aacgtt', len: 6 },
  { name: 'SlaI', reg: 'ctcgag', len: 6 },
  { name: 'SduI', reg: 'g[agt]gc[act]c', len: 6 },
  { name: 'BfaI', reg: 'ctag', len: 4 },
  { name: 'Cac8I', reg: 'gc[actg][actg]gc', len: 6 },
  { name: 'TaaI', reg: 'ac[actg]gt', len: 5 },
  { name: 'PflFI', reg: 'gac[actg][actg][actg]gtc', len: 9 },
  { name: 'PpuXI', reg: '[ag]gg[at]cc[ct]', len: 7 },
  { name: 'PvuI', reg: 'cgatcg', len: 6 },
  { name: 'DraII', reg: '[ag]gg[actg]cc[ct]', len: 7 },
  { name: 'SnaBI', reg: 'tacgta', len: 6 },
  { name: 'MlsI', reg: 'tggcca', len: 6 },
  { name: 'RsaI', reg: 'gtac', len: 4 },
  { name: 'XapI', reg: '[ag]aatt[ct]', len: 6 },
  { name: 'Asp700I',
    reg: 'gaa[actg][actg][actg][actg]ttc',
    len: 10 },
  { name: 'CviRI', reg: 'tgca', len: 4 },
  { name: 'EcoRV', reg: 'gatatc', len: 6 },
  { name: 'XhoI', reg: 'ctcgag', len: 6 },
  { name: 'Sse8387I', reg: 'cctgcagg', len: 8 },
  { name: 'Eco105I', reg: 'tacgta', len: 6 },
  { name: 'NspIII', reg: 'c[ct]cg[ag]g', len: 6 },
  { name: 'BsaWI', reg: '[at]ccgg[at]', len: 6 },
  { name: 'Ecl136II', reg: 'gagctc', len: 6 },
  { name: 'MluI', reg: 'acgcgt', len: 6 },
  { name: 'BstPI', reg: 'ggt[actg]acc', len: 7 },
  { name: 'BsiYI',
    reg: 'cc[actg][actg][actg][actg][actg][actg][actg]gg',
    len: 11 },
  { name: 'MroNI', reg: 'gccggc', len: 6 },
  { name: 'MscI', reg: 'tggcca', len: 6 },
  { name: 'PalI', reg: 'ggcc', len: 4 },
  { name: 'XspI', reg: 'ctag', len: 4 },
  { name: 'FblI', reg: 'gt[ac][gt]ac', len: 6 },
  { name: 'SpeI', reg: 'actagt', len: 6 },
  { name: 'HinP1I', reg: 'gcgc', len: 4 },
  { name: 'PhoI', reg: 'ggcc', len: 4 },
  { name: 'XmaJI', reg: 'cctagg', len: 6 },
  { name: 'Hsp92I', reg: 'g[ag]cg[ct]c', len: 6 },
  { name: 'BstNSI', reg: '[ag]catg[ct]', len: 6 },
  { name: 'FauNDI', reg: 'catatg', len: 6 },
  { name: 'AspS9I', reg: 'gg[actg]cc', len: 5 },
  { name: 'Cfr10I', reg: '[ag]ccgg[ct]', len: 6 },
  { name: 'MseI', reg: 'ttaa', len: 4 },
  { name: 'PspDI', reg: 'tcgcga', len: 6 },
  { name: 'BlnI', reg: 'cctagg', len: 6 },
  { name: 'BspXI', reg: 'atcgat', len: 6 },
  { name: 'NsiI', reg: 'atgcat', len: 6 },
  { name: 'Fsp4HI', reg: 'gc[actg]gc', len: 5 },
  { name: 'PauI', reg: 'gcgcgc', len: 6 },
  { name: 'DriI',
    reg: 'gac[actg][actg][actg][actg][actg]gtc',
    len: 11 },
  { name: 'SfiI',
    reg: 'ggcc[actg][actg][actg][actg][actg]ggcc',
    len: 13 },
  { name: 'BstHHI', reg: 'gcgc', len: 4 },
  { name: 'BglI',
    reg: 'gcc[actg][actg][actg][actg][actg]ggc',
    len: 11 },
  { name: 'SfoI', reg: 'ggcgcc', len: 6 },
  { name: 'PaeI', reg: 'gcatgc', len: 6 },
  { name: 'Bsh1236I', reg: 'cgcg', len: 4 },
  { name: 'Bst98I', reg: 'cttaag', len: 6 },
  { name: 'SbfI', reg: 'cctgcagg', len: 8 },
  { name: 'Bbv12I', reg: 'g[at]gc[at]c', len: 6 },
  { name: 'Eco47III', reg: 'agcgct', len: 6 },
  { name: 'EcoNI',
    reg: 'cct[actg][actg][actg][actg][actg]agg',
    len: 11 },
  { name: 'AccIII', reg: 'tccgga', len: 6 },
  { name: 'Sfr303I', reg: 'ccgcgg', len: 6 },
  { name: 'Tsp509I', reg: 'aatt', len: 4 },
  { name: 'NgoMIV', reg: 'gccggc', len: 6 },
  { name: 'BbrPI', reg: 'cacgtg', len: 6 },
  { name: 'HpyCH4IV', reg: 'acgt', len: 4 },
  { name: 'Acc65I', reg: 'ggtacc', len: 6 },
  { name: 'AgeI', reg: 'accggt', len: 6 },
  { name: 'BsaAI', reg: '[ct]acgt[ag]', len: 6 },
  { name: 'BstH2I', reg: '[ag]gcgc[ct]', len: 6 },
  { name: 'BmtI', reg: 'gctagc', len: 6 },
  { name: 'BstSNI', reg: 'tacgta', len: 6 },
  { name: 'BbuI', reg: 'gcatgc', len: 6 },
  { name: 'StyI', reg: 'cc[at][at]gg', len: 6 },
  { name: 'AviII', reg: 'tgcgca', len: 6 },
  { name: 'BfrI', reg: 'cttaag', len: 6 },
  { name: 'Bst2UI', reg: 'cc[at]gg', len: 5 },
  { name: 'BslI',
    reg: 'cc[actg][actg][actg][actg][actg][actg][actg]gg',
    len: 11 },
  { name: 'Tru9I', reg: 'ttaa', len: 4 },
  { name: 'BspMAI', reg: 'ctgcag', len: 6 },
  { name: 'BsuRI', reg: 'ggcc', len: 4 },
  { name: 'CfrI', reg: '[ct]ggcc[ag]', len: 6 },
  { name: 'SanDI', reg: 'ggg[at]ccc', len: 7 },
  { name: 'BglII', reg: 'agatct', len: 6 },
  { name: 'NsbI', reg: 'tgcgca', len:6 },
  { name: 'AsuII', reg: 'ttcgaa', len: 6 },
  { name: 'BstZ17I', reg: 'gtatac', len: 6 },
  { name: 'ZrmI', reg: 'agtact', len: 6 },
  { name: 'AspA2I', reg: 'cctagg', len: 6 },
  { name: 'MspI', reg: 'ccgg', len: 4 },
  { name: 'KspI', reg: 'ccgcgg', len: 6 },
  { name: 'TspEI', reg: 'aatt', len: 4 },
  { name: 'BsaHI', reg: 'g[ag]cg[ct]c', len: 6 },
  { name: 'DraIII', reg: 'cac[actg][actg][actg]gtg', len: 9 },
  { name: 'EcoICRI', reg: 'gagctc', len: 6 },
  { name: 'BstNI', reg: 'cc[at]gg', len: 5 },
  { name: 'AcvI', reg: 'cacgtg', len: 6 },
  { name: 'Eco72I', reg: 'cacgtg', len: 6 },
  { name: 'EheI', reg: 'ggcgcc', len: 6 },
  { name: 'Bsp19I', reg: 'ccatgg', len: 6 },
  { name: 'Eco32I', reg: 'gatatc', len: 6 }
  ]
  return enzymes;
})